<a href="https://colab.research.google.com/github/Gaabi1/pandas-python/blob/main/pythonAnalise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instalção e Importação

In [ ]:
import pandas as pd

Fazer upload manual

In [ ]:
from google.colab import files

Faz upload do arquivo

In [ ]:
unploaded = files.upload()

Saving dados_empresa.xlsx to dados_empresa.xlsx
Saving departamentos.csv to departamentos.csv
Saving funcionarios.csv to funcionarios.csv
Saving funcionarios_nulos.csv to funcionarios_nulos.csv
Saving novos_funcionarios.csv to novos_funcionarios.csv
Saving pandas em poucos minutos.ipynb to pandas em poucos minutos.ipynb
Saving todos_funcionarios.csv to todos_funcionarios.csv

Lendo Tabelas

In [ ]:
df = pd.read_csv('funcionarios.csv')
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

Manipulação Básica de Dados

In [ ]:
#Primeiras 5 linhas
df.head()

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4

In [ ]:
#Ultimas 5 linha
df.tail()

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

In [ ]:
#Selecionar colunas especificas
df[['Nome', 'Idade']]

                         Nome  Idade
0    Sra. Isabela Vasconcelos     44
1             Heitor Teixeira     40
2          Bianca Vasconcelos     44
3               Alice Machado     40
4           Antônio Fernandes     54
5       Henry Gabriel da Mata     42
6   Sra. Maria Luiza Oliveira     58
7                Isis Marques     24
8           Sr. Vitor da Rosa     61
9                Théo Cardoso     54
10          Marcelo Rodrigues     57
11         Maria Clara Santos     39
12                 Sofia Rios     45
13          Benicio das Neves     22
14              Levi Silveira     42
15     Maria Fernanda Rezende     29
16         Thomas Casa Grande     33
17        Davi Miguel Ribeiro     48
18     Dr. Mathias Montenegro     20
19           Samuel Gonçalves     21

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df[['Idade']]

    Idade
0      44
1      40
2      44
3      40
4      54
5      42
6      58
7      24
8      61
9      54
10     57
11     39
12     45
13     22
14     42
15     29
16     33
17     48
18     20
19     21

In [ ]:
df[df['Idade'] > 30]

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5

In [ ]:
df[df['Salário'] > 3000]

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

Combinando filtro

In [ ]:
filtro_maior_30 = df['Idade'] > 30
filtro_mais_3000 = df['Salário'] > 3000

df[filtro_maior_30 & filtro_mais_3000]

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2

Criando e Removendo Colunas

In [ ]:
#Criando coluna salário anual
df['Salário Anual'] = df['Salário'] * 12
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento,Salário Anual
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4,53221.56
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2,94019.64
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2,37134.60
3,4,Alice Machado,40,2023-10-10,6287.20,True,2,75446.40
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4,85661.16
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4,59299.44
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5,85335.00
7,8,Isis Marques,24,2023-02-05,8438.66,True,1,101263.92
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1,28366.20
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2,96355.80
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1,97312.20
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4,31220.16
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1,59880.12
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5,30498.48
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5,111143.76
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3,89234.52
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2,98470.80
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5,31500.12
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4,114801.96
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3,46619.88

In [ ]:
#Removendo a coluna
df = df.drop('Salário Anual', axis=1)
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

Resumindo Dados

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                20 non-null     int64
 1   Nome              20 non-null     object
 2   Idade             20 non-null     int64
 3   Data de Registro  20 non-null     object
 4   Salário           20 non-null     float64
 5   Ativo             20 non-null     bool
 6   ID Departamento   20 non-null     int64
dtypes: bool(1), float64(1), int64(3), object(2)
memory usage: 1.1+ KB

In [ ]:
df.describe()

             ID      Idade      Salário  ID Departamento
count  20.00000  20.000000    20.000000        20.000000
mean   10.50000  40.850000  5944.940500         3.000000
std     5.91608  12.716649  2474.638644         1.486784
min     1.00000  20.000000  2363.850000         1.000000
25%     5.75000  32.000000  3687.380000         2.000000
50%    10.50000  42.000000  6699.225000         3.000000
75%    15.25000  49.500000  8049.575000         4.000000
max    20.00000  61.000000  9566.830000         5.000000

In [ ]:
#Soma de Salários
df['Salário'].sum()

np.float64(118898.80999999998)

In [ ]:
#Média de Salários
df['Salário'].mean()

np.float64(5944.940499999999)

In [ ]:
#Salário Max
df['Salário'].max()

9566.83

In [ ]:
df['Salário'].min()

2363.85

Limpeza de Dados

In [ ]:
df = pd.read_csv('funcionarios_nulos.csv')
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,NaN,35.0,2024-01-02,5469.47,True,3.0
1,2,Nicolas Cardoso,45.0,2022-05-25,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60.0,2023-01-05,5599.99,True,4.0
3,4,Luiz Fernando Fernandes,NaN,2023-10-09,6708.07,False,NaN
4,5,Gael Henrique Costela,51.0,2021-11-07,9497.52,NaN,NaN
5,6,Stephany Pimenta,32.0,2024-07-21,7123.00,True,NaN
6,7,Bruna Vargas,25.0,2022-03-29,5036.81,NaN,NaN
7,8,NaN,60.0,2024-03-03,8219.79,True,5.0
8,9,NaN,47.0,2022-09-12,4790.53,NaN,4.0
9,10,NaN,NaN,2022-06-26,8914.27,NaN,4.0
10,11,NaN,NaN,2023-02-04,4475.88,NaN,NaN
11,12,Manuela Guerra,NaN,2022-03-31,9883.09,False,NaN
12,13,Dr. Apollo Moraes,NaN,2023-01-16,5392.79,True,NaN
13,14,Antônio Gonçalves,44.0,NaN,5511.17,True,NaN
14,15,Luara Lima,48.0,NaN,5426.62,True,3.0
15,16,NaN,26.0,NaN,6519.70,False,NaN
16,17,NaN,41.0,2024-07-11,7815.03,False,5.0
17,18,Isabela Campos,28.0,2022-06-21,7824.41,False,4.0
18,19,Danilo Rocha,32.0,2024-08-07,7196.97,False,4.0
19,20,Sara Fonseca,50.0,2023-09-05,5884.55,True,2.0

In [ ]:
df.dropna()

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
1,2,Nicolas Cardoso,45.0,2022-05-25,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60.0,2023-01-05,5599.99,True,4.0
17,18,Isabela Campos,28.0,2022-06-21,7824.41,False,4.0
18,19,Danilo Rocha,32.0,2024-08-07,7196.97,False,4.0
19,20,Sara Fonseca,50.0,2023-09-05,5884.55,True,2.0

In [ ]:
#Remover só as linha que tem valores nulos pra coluna idade
df.dropna(subset="Idade")

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,NaN,35.0,2024-01-02,5469.47,True,3.0
1,2,Nicolas Cardoso,45.0,2022-05-25,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60.0,2023-01-05,5599.99,True,4.0
4,5,Gael Henrique Costela,51.0,2021-11-07,9497.52,NaN,NaN
5,6,Stephany Pimenta,32.0,2024-07-21,7123.00,True,NaN
6,7,Bruna Vargas,25.0,2022-03-29,5036.81,NaN,NaN
7,8,NaN,60.0,2024-03-03,8219.79,True,5.0
8,9,NaN,47.0,2022-09-12,4790.53,NaN,4.0
13,14,Antônio Gonçalves,44.0,NaN,5511.17,True,NaN
14,15,Luara Lima,48.0,NaN,5426.62,True,3.0
15,16,NaN,26.0,NaN,6519.70,False,NaN
16,17,NaN,41.0,2024-07-11,7815.03,False,5.0
17,18,Isabela Campos,28.0,2022-06-21,7824.41,False,4.0
18,19,Danilo Rocha,32.0,2024-08-07,7196.97,False,4.0
19,20,Sara Fonseca,50.0,2023-09-05,5884.55,True,2.0

In [ ]:
#Preencher os valores nulos com outros valores
media_valores= df['Idade'].mean()
df['Idade'] = df['Idade'].fillna(media_valores)
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,NaN,35.0,2024-01-02,5469.47,True,3.0
1,2,Nicolas Cardoso,45.0,2022-05-25,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60.0,2023-01-05,5599.99,True,4.0
3,4,Luiz Fernando Fernandes,41.6,2023-10-09,6708.07,False,NaN
4,5,Gael Henrique Costela,51.0,2021-11-07,9497.52,NaN,NaN
5,6,Stephany Pimenta,32.0,2024-07-21,7123.00,True,NaN
6,7,Bruna Vargas,25.0,2022-03-29,5036.81,NaN,NaN
7,8,NaN,60.0,2024-03-03,8219.79,True,5.0
8,9,NaN,47.0,2022-09-12,4790.53,NaN,4.0
9,10,NaN,41.6,2022-06-26,8914.27,NaN,4.0
10,11,NaN,41.6,2023-02-04,4475.88,NaN,NaN
11,12,Manuela Guerra,41.6,2022-03-31,9883.09,False,NaN
12,13,Dr. Apollo Moraes,41.6,2023-01-16,5392.79,True,NaN
13,14,Antônio Gonçalves,44.0,NaN,5511.17,True,NaN
14,15,Luara Lima,48.0,NaN,5426.62,True,3.0
15,16,NaN,26.0,NaN,6519.70,False,NaN
16,17,NaN,41.0,2024-07-11,7815.03,False,5.0
17,18,Isabela Campos,28.0,2022-06-21,7824.41,False,4.0
18,19,Danilo Rocha,32.0,2024-08-07,7196.97,False,4.0
19,20,Sara Fonseca,50.0,2023-09-05,5884.55,True,2.0

In [ ]:
#Trocar tipos de Dados
df['Idade'] = df['Idade'].astype(int)
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,NaN,35,2024-01-02,5469.47,True,3.0
1,2,Nicolas Cardoso,45,2022-05-25,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60,2023-01-05,5599.99,True,4.0
3,4,Luiz Fernando Fernandes,41,2023-10-09,6708.07,False,NaN
4,5,Gael Henrique Costela,51,2021-11-07,9497.52,NaN,NaN
5,6,Stephany Pimenta,32,2024-07-21,7123.00,True,NaN
6,7,Bruna Vargas,25,2022-03-29,5036.81,NaN,NaN
7,8,NaN,60,2024-03-03,8219.79,True,5.0
8,9,NaN,47,2022-09-12,4790.53,NaN,4.0
9,10,NaN,41,2022-06-26,8914.27,NaN,4.0
10,11,NaN,41,2023-02-04,4475.88,NaN,NaN
11,12,Manuela Guerra,41,2022-03-31,9883.09,False,NaN
12,13,Dr. Apollo Moraes,41,2023-01-16,5392.79,True,NaN
13,14,Antônio Gonçalves,44,NaN,5511.17,True,NaN
14,15,Luara Lima,48,NaN,5426.62,True,3.0
15,16,NaN,26,NaN,6519.70,False,NaN
16,17,NaN,41,2024-07-11,7815.03,False,5.0
17,18,Isabela Campos,28,2022-06-21,7824.41,False,4.0
18,19,Danilo Rocha,32,2024-08-07,7196.97,False,4.0
19,20,Sara Fonseca,50,2023-09-05,5884.55,True,2.0

Contando Ocorrências

In [ ]:
df = pd.read_csv('funcionarios.csv')

In [ ]:
#Conta funcionarios ativos
df['Ativo'].value_counts()

Ativo
True     9
False    6
Name: count, dtype: int64

In [ ]:
#Numero de funcionarios em cada departamento
df['ID Departamento'].value_counts()

ID Departamento
4.0    6
3.0    2
5.0    2
2.0    1
Name: count, dtype: int64

Operações de Agregação

In [ ]:
df.groupby('ID Departamento')

In [ ]:
#Média salária por departamento
df.groupby('ID Departamento')['Salário'].mean()

ID Departamento
2.0     5884.55
3.0    10896.09
4.0    38150.37
5.0    16034.82
Name: Salário, dtype: float64

In [ ]:
df.groupby('ID Departamento')['Salário'].sum()

ID Departamento
2.0     5884.55
3.0    10896.09
4.0    38150.37
5.0    16034.82
Name: Salário, dtype: float64

In [ ]:
df.groupby('ID Departamento')['Salário'].max()

ID Departamento
2.0    5884.55
3.0    5469.47
4.0    8914.27
5.0    8219.79
Name: Salário, dtype: float64

Ordenando Dados

In [ ]:
#Do menor pro maior
df.sort_values(by='Salário')

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
1,2,Nicolas Cardoso,45,2022-05-25,3824.20,True,4.0
10,11,NaN,41,2023-02-04,4475.88,NaN,NaN
8,9,NaN,47,2022-09-12,4790.53,NaN,4.0
6,7,Bruna Vargas,25,2022-03-29,5036.81,NaN,NaN
12,13,Dr. Apollo Moraes,41,2023-01-16,5392.79,True,NaN
14,15,Luara Lima,48,NaN,5426.62,True,3.0
0,1,NaN,35,2024-01-02,5469.47,True,3.0
13,14,Antônio Gonçalves,44,NaN,5511.17,True,NaN
2,3,Lucas Gabriel Sampaio,60,2023-01-05,5599.99,True,4.0
19,20,Sara Fonseca,50,2023-09-05,5884.55,True,2.0
15,16,NaN,26,NaN,6519.70,False,NaN
3,4,Luiz Fernando Fernandes,41,2023-10-09,6708.07,False,NaN
5,6,Stephany Pimenta,32,2024-07-21,7123.00,True,NaN
18,19,Danilo Rocha,32,2024-08-07,7196.97,False,4.0
16,17,NaN,41,2024-07-11,7815.03,False,5.0
17,18,Isabela Campos,28,2022-06-21,7824.41,False,4.0
7,8,NaN,60,2024-03-03,8219.79,True,5.0
9,10,NaN,41,2022-06-26,8914.27,NaN,4.0
4,5,Gael Henrique Costela,51,2021-11-07,9497.52,NaN,NaN
11,12,Manuela Guerra,41,2022-03-31,9883.09,False,NaN

In [ ]:
#Do maior pro menor
df.sort_values(by='Salário', ascending=False)

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
11,12,Manuela Guerra,41,2022-03-31,9883.09,False,NaN
4,5,Gael Henrique Costela,51,2021-11-07,9497.52,NaN,NaN
9,10,NaN,41,2022-06-26,8914.27,NaN,4.0
7,8,NaN,60,2024-03-03,8219.79,True,5.0
17,18,Isabela Campos,28,2022-06-21,7824.41,False,4.0
16,17,NaN,41,2024-07-11,7815.03,False,5.0
18,19,Danilo Rocha,32,2024-08-07,7196.97,False,4.0
5,6,Stephany Pimenta,32,2024-07-21,7123.00,True,NaN
3,4,Luiz Fernando Fernandes,41,2023-10-09,6708.07,False,NaN
15,16,NaN,26,NaN,6519.70,False,NaN
19,20,Sara Fonseca,50,2023-09-05,5884.55,True,2.0
2,3,Lucas Gabriel Sampaio,60,2023-01-05,5599.99,True,4.0
13,14,Antônio Gonçalves,44,NaN,5511.17,True,NaN
0,1,NaN,35,2024-01-02,5469.47,True,3.0
14,15,Luara Lima,48,NaN,5426.62,True,3.0
12,13,Dr. Apollo Moraes,41,2023-01-16,5392.79,True,NaN
6,7,Bruna Vargas,25,2022-03-29,5036.81,NaN,NaN
8,9,NaN,47,2022-09-12,4790.53,NaN,4.0
10,11,NaN,41,2023-02-04,4475.88,NaN,NaN
1,2,Nicolas Cardoso,45,2022-05-25,3824.20,True,4.0

Combinando Dados

In [ ]:
df_depart = pd.read_csv('departamentos.csv')
df_depart

   ID Departamento Nome Departamento
0                1            Vendas
1                2                TI
2                3                RH
3                4        Financeiro
4                5         Marketing

In [ ]:
df_final = pd.merge(df, df_depart)
df_final

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento,Nome Departamento
0,1,NaN,35,2024-01-02,5469.47,True,3.0,RH
1,2,Nicolas Cardoso,45,2022-05-25,3824.20,True,4.0,Financeiro
2,3,Lucas Gabriel Sampaio,60,2023-01-05,5599.99,True,4.0,Financeiro
3,8,NaN,60,2024-03-03,8219.79,True,5.0,Marketing
4,9,NaN,47,2022-09-12,4790.53,NaN,4.0,Financeiro
5,10,NaN,41,2022-06-26,8914.27,NaN,4.0,Financeiro
6,15,Luara Lima,48,NaN,5426.62,True,3.0,RH
7,17,NaN,41,2024-07-11,7815.03,False,5.0,Marketing
8,18,Isabela Campos,28,2022-06-21,7824.41,False,4.0,Financeiro
9,19,Danilo Rocha,32,2024-08-07,7196.97,False,4.0,Financeiro
10,20,Sara Fonseca,50,2023-09-05,5884.55,True,2.0,TI

In [ ]:
#Especificar caso as duas tabelas não fossem iguais
df_final = pd.merge(df, df_depart, left_on='ID Departamento', right_on='ID Departamento')
df_final

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento,Nome Departamento
0,1,NaN,35,2024-01-02,5469.47,True,3.0,RH
1,2,Nicolas Cardoso,45,2022-05-25,3824.20,True,4.0,Financeiro
2,3,Lucas Gabriel Sampaio,60,2023-01-05,5599.99,True,4.0,Financeiro
3,8,NaN,60,2024-03-03,8219.79,True,5.0,Marketing
4,9,NaN,47,2022-09-12,4790.53,NaN,4.0,Financeiro
5,10,NaN,41,2022-06-26,8914.27,NaN,4.0,Financeiro
6,15,Luara Lima,48,NaN,5426.62,True,3.0,RH
7,17,NaN,41,2024-07-11,7815.03,False,5.0,Marketing
8,18,Isabela Campos,28,2022-06-21,7824.41,False,4.0,Financeiro
9,19,Danilo Rocha,32,2024-08-07,7196.97,False,4.0,Financeiro
10,20,Sara Fonseca,50,2023-09-05,5884.55,True,2.0,TI

Empilhando

In [ ]:
df_novos= pd.read_csv('novos_funcionarios.csv')
df_novos

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Maria Clara Cunha,27,2023-03-05,6747.76,True,4
1,2,Luiz Gustavo Barros,18,2022-11-11,5990.81,False,3
2,3,Maria Helena das Neves,19,2024-04-01,7588.55,False,5
3,4,Ravy Camargo,36,2022-01-25,4341.11,False,4
4,5,Cecilia Casa Grande,46,2022-10-30,5716.84,True,4
5,6,Carolina Souza,62,2022-05-02,3305.85,False,4
6,7,Mathias Souza,28,2024-05-02,9782.90,True,4
7,8,Yago Gomes,28,2023-10-17,9615.18,True,1
8,9,Natália Moraes,20,2022-10-03,2798.04,True,5
9,10,João Miguel Caldeira,53,2024-03-12,8941.77,True,1
10,11,Thales Monteiro,55,2022-05-20,7587.85,True,2
11,12,Miguel Pacheco,61,2022-12-22,7690.91,False,2
12,13,Léo da Conceição,40,2023-01-20,7552.60,True,3
13,14,Aurora Carvalho,53,2022-03-27,2954.14,True,1
14,15,Mathias Rocha,44,2024-01-18,9316.01,True,5
15,16,Maria Liz Sampaio,34,2023-12-01,8334.63,False,2
16,17,Arthur Gabriel Cassiano,42,2024-03-23,4275.55,False,4
17,18,Joana Sousa,54,2023-05-20,5755.79,True,5
18,19,Srta. Ana Lívia Silva,21,2023-11-19,7636.43,False,5
19,20,Gustavo Castro,64,2022-02-04,3641.82,True,2

In [ ]:
#Uni tudo verticalmente e recria id do zero
df_todos= pd.concat([df, df_novos], ignore_index=True)
df_todos

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,NaN,35,2024-01-02,5469.47,True,3.0
1,2,Nicolas Cardoso,45,2022-05-25,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60,2023-01-05,5599.99,True,4.0
3,4,Luiz Fernando Fernandes,41,2023-10-09,6708.07,False,NaN
4,5,Gael Henrique Costela,51,2021-11-07,9497.52,NaN,NaN
5,6,Stephany Pimenta,32,2024-07-21,7123.00,True,NaN
6,7,Bruna Vargas,25,2022-03-29,5036.81,NaN,NaN
7,8,NaN,60,2024-03-03,8219.79,True,5.0
8,9,NaN,47,2022-09-12,4790.53,NaN,4.0
9,10,NaN,41,2022-06-26,8914.27,NaN,4.0
10,11,NaN,41,2023-02-04,4475.88,NaN,NaN
11,12,Manuela Guerra,41,2022-03-31,9883.09,False,NaN
12,13,Dr. Apollo Moraes,41,2023-01-16,5392.79,True,NaN
13,14,Antônio Gonçalves,44,NaN,5511.17,True,NaN
14,15,Luara Lima,48,NaN,5426.62,True,3.0
15,16,NaN,26,NaN,6519.70,False,NaN
16,17,NaN,41,2024-07-11,7815.03,False,5.0
17,18,Isabela Campos,28,2022-06-21,7824.41,False,4.0
18,19,Danilo Rocha,32,2024-08-07,7196.97,False,4.0
19,20,Sara Fonseca,50,2023-09-05,5884.55,True,2.0
20,1,Maria Clara Cunha,27,2023-03-05,6747.76,True,4.0
21,2,Luiz Gustavo Barros,18,2022-11-11,5990.81,False,3.0
22,3,Maria Helena das Neves,19,2024-04-01,7588.55,False,5.0
23,4,Ravy Camargo,36,2022-01-25,4341.11,False,4.0
24,5,Cecilia Casa Grande,46,2022-10-30,5716.84,True,4.0
25,6,Carolina Souza,62,2022-05-02,3305.85,False,4.0
26,7,Mathias Souza,28,2024-05-02,9782.90,True,4.0
27,8,Yago Gomes,28,2023-10-17,9615.18,True,1.0
28,9,Natália Moraes,20,2022-10-03,2798.04,True,5.0
29,10,João Miguel Caldeira,53,2024-03-12,8941.77,True,1.0
30,11,Thales Monteiro,55,2022-05-20,7587.85,True,2.0
31,12,Miguel Pacheco,61,2022-12-22,7690.91,False,2.0
32,13,Léo da Conceição,40,2023-01-20,7552.60,True,3.0
33,14,Aurora Carvalho,53,2022-03-27,2954.14,True,1.0
34,15,Mathias Rocha,44,2024-01-18,9316.01,True,5.0
35,16,Maria Liz Sampaio,34,2023-12-01,8334.63,False,2.0
36,17,Arthur Gabriel Cassiano,42,2024-03-23,4275.55,False,4.0
37,18,Joana Sousa,54,2023-05-20,5755.79,True,5.0
38,19,Srta. Ana Lívia Silva,21,2023-11-19,7636.43,False,5.0
39,20,Gustavo Castro,64,2022-02-04,3641.82,True,2.0

Escrevendo dados em arquivo

In [ ]:
df_todos.to_csv('funcionarios_final.csv')